### ISSUE TITLE
Deterministic random 2d points for voronoi input

### ISSUE THREAD

**Issue by Zalastax** [DATX02-16-86/Code#10]
When generating the voronoi diagram we need input points that are deterministic for a given area. A suitable 2d noise function sampled for each point with a threshold for including the point seems simplest. Do we know of any 2D noise functions that doesn't cause grouping? An alternative could be to seed a normal pseudo random function with coordinates of the area.

**Comment by Zalastax** [comment]
Using a standard random generator and a seed based on the chunk coordinates seem to work fine. @lidin are you satisfied with the results?

**Comment by hampuslidin** [comment]
@Zalastax I haven't been able to work on the project this weekend due to exam on Monday, but I will look into it.

**Comment by Zalastax** [comment]
Looking more into it I have found (as many others) that psueo-random numbers tend to cause clumping which doesn't look nice. I didn't find any good quasi-random/blue noise generators for C++. http://www.redblobgames.com/articles/noise/introduction.html#functions https://en.wikipedia.org/wiki/Low-discrepancy_sequence
